name: uoc20222pec1
channels:
  - defaults
dependencies:
  - scikit-learn=1.0.2
  - python=3.9.7
  - seaborn=0.11.2
  - matplotlib=3.5.1
  - jupyter=1.0.0
  - numpy=1.21.2
  - pandas=1.4.1
  - pydotplus=2.0.2
