name: uoc20222pec2
channels:
  - defaults
dependencies:
  - scikit-learn=0.24.1
  - scikit-image=0.19.3
  - ffmpeg=4.2.2
  - python=3.9.1
  - seaborn=0.11.1
  - matplotlib=3.3.4
  - jupyter=1.0.0
  - numpy=1.19.2
  - pandas=1.2.2
  - plotly=5.6.0
  - scipy=1.6.2
  - tqdm=4.63.0
  - pip=21.2.4
  - pip:
    - umap-learn==0.5.1
    - smopy==0.0.7
    - haversine==2.7.0
