name: uoc20222pec4
channels:
  - defaults
dependencies:
  - scikit-learn=1.2.2
  - python=3.9.7
  - seaborn=0.11.2
  - matplotlib=3.5.1
  - jupyter=1.0.0
  - numpy=1.21.2
  - pandas=1.5.3
  - pydotplus=2.0.2
